merge upstream updates

diff --git a/.gitlab/ci/templates.yml b/.gitlab/ci/templates.yml
--- a/.gitlab/ci/templates.yml
+++ b/.gitlab/ci/templates.yml
@@ -1,6 +1,6 @@
 variables:
   ## This value MUST be the same as `opam_repository_tag` in `scripts/version.sh`
-  build_deps_image_version: 8c079ce574eb9097edf48c39fecff2aefb960229
+  build_deps_image_version: b53a5e8c3fa7764d5ae6567d7a817315507c9f0d
   build_deps_image_name: registry.gitlab.com/tezos/opam-repository
   GIT_STRATEGY: fetch
   GIT_DEPTH: "1"
@@ -76,12 +76,20 @@ variables:
       when: never
     - if: '$CI_COMMIT_TAG && $CI_PROJECT_NAMESPACE == $TEZOS_DEFAULT_NAMESPACE'
       when: on_success
+      variables:
+        MASTER_OR_RELEASE: "true"
     - if: '($CI_COMMIT_BRANCH =~ /-release$/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /-release$/) && $CI_PROJECT_NAMESPACE == $TEZOS_DEFAULT_NAMESPACE'
       when: on_success
+      variables:
+        MASTER_OR_RELEASE: "true"
     - if: '$CI_COMMIT_BRANCH == $TEZOS_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == $TEZOS_DEFAULT_NAMESPACE'
       when: on_success
+      variables:
+        MASTER_OR_RELEASE: "true"
     - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $TEZOS_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == $TEZOS_DEFAULT_NAMESPACE'
       when: on_success
+      variables:
+        MASTER_OR_RELEASE: "true"
     - when: never
 
 # Rules for all the jobs that are run only for the master branch
@@ -125,20 +133,11 @@ variables:
     - when: manual
       allow_failure: true
 
-.rules_template__development_coverage:
-  rules:
-    - if: '$TZ_PIPELINE_KIND == "SCHEDULE" && $TZ_SCHEDULE_KIND == "EXTENDED_TESTS"'
-      when: always
-    - when: manual
-      allow_failure: true
-
+# The job `unified_coverage` runs on master and one development pipelines. It
+# runs on merge requests, unless the `ci--no-coverage` tag is set.
 .rules_template__development_unified_coverage:
   rules:
     - if: '$TZ_PIPELINE_KIND == "SCHEDULE"'
-      when: never
-    - if: '$CI_COMMIT_BRANCH == $TEZOS_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == $TEZOS_DEFAULT_NAMESPACE'
-      when: never
-    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == $TEZOS_DEFAULT_BRANCH && $CI_PROJECT_NAMESPACE == $TEZOS_DEFAULT_NAMESPACE'
       when: never
     - if: '($CI_COMMIT_BRANCH =~ /-release$/ || $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /-release$/) && $CI_PROJECT_NAMESPACE == $TEZOS_DEFAULT_NAMESPACE'
       when: never
@@ -210,7 +209,7 @@ variables:
 # Job templates
 
 # This template is used by the opam test jobs in the child pipeline
-# triggered by `bootstrap-opam-pipeline.yml`.
+# triggered by `packaging.yml`.
 .opam_template:
   extends:
     - .default_settings_template
@@ -220,6 +219,12 @@ variables:
     # the child pipeline triggerer (`opam:trigger`).
     - .rules_template__trigger_opam_pipeline
   stage: packaging
+  # FIXME: https://gitlab.com/nomadic-labs/tezos/-/issues/663
+  # FIXME: https://gitlab.com/nomadic-labs/tezos/-/issues/664
+  # At the time of writing, the opam tests were quite flaky.
+  # Therefore, a retry was added. This should be removed once the
+  # underlying tests have been fixed.
+  retry: 2
   script:
     - ./scripts/opam-pin.sh
     - opam depext --yes ${package}
@@ -258,3 +263,44 @@ variables:
       - $BISECT_FILE
     expire_in: 1 day
     when: on_success
+
+.build_template:
+  extends:
+    - .default_settings_template
+    - .image_template__runtime_build_test_dependencies_template
+    - .template__coverage
+  stage: build
+  before_script:
+    - . ./scripts/version.sh
+    # Load the environment poetry previously created in the docker image.
+    # Give access to the Python dependencies/executables
+    - . $HOME/.venv/bin/activate
+
+# Setup authentication for either Docker Hub (release) or GitLab registry (dev).
+# Also setup Docker names such that they are valid for the target (Docker Hub or GitLab).
+# Docker constraints on tags: https://docs.docker.com/engine/reference/commandline/tag/
+#
+#   A tag name must be valid ASCII and may contain lowercase and
+#   uppercase letters, digits, underscores, periods and dashes. A tag
+#   name may not start with a period or a dash and may contain a maximum
+#   of 128 characters.
+#
+# To detect dev mode we test the value of $CI_REGISTRY.
+# GitLab image name must follow this format:
+# https://docs.gitlab.com/ee/user/packages/container_registry/#image-naming-convention
+.docker_registry_auth:
+  before_script:
+    - mkdir ~/.docker || true
+    - if [ "$MASTER_OR_RELEASE" = "true" ]; then
+        export DOCKER_IMAGE_NAME="docker.io/${CI_PROJECT_PATH}-" ;
+        echo "{ \"auths\":{ \"https://index.docker.io/v1/\":{ \"auth\":\"${CI_DOCKER_AUTH}\" } } }" > ~/.docker/config.json ;
+      else
+        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY ;
+        export DOCKER_IMAGE_NAME="${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/" ;
+      fi
+    - TAG_NAME=$(echo "${IMAGE_ARCH_PREFIX}${CI_COMMIT_REF_NAME}" | tr -c -- '-._\n[:alnum:]' '_')
+    - echo "Building images ${DOCKER_IMAGE_NAME%?} ( /bare & /debug ) ${TAG_NAME}"
+
+.template__code_quality:
+  variables:
+    CODE_QUALITY_REPORT: "_reports/gl-code-quality-report.json"
